;; Note:
;;   Install color-theme and color-theme-solarized from Packages List
;;   Add path to this file to 'load-path
;;     (add-to-list 'load-path "/path/to/this/file")
;;   then
;;     (load "tnt_color-theme.el")

(defun color-theme-tuantran ()
  (color-theme-install
   '(color-theme-tuantran
     ((mouse-color . "#000000000000")
      (cursor-color . "#E5E5E5E5E5E5")
      (border-color . "#000000000000")
      (background-mode . dark))
     (default ((t (:background "#000000000000" :foreground "#FFFFFFFFD7D7"))))
     (modeline ((t (:foreground "#000000000000" :background "#FFFFD7D7AFAF"))))
     (modeline-buffer-id ((t (:foreground "#000000000000" :background "#FFFFD7D7AFAF"))))
     (modeline-mousable ((t (:foreground "#000000000000" :background "#FFFFD7D7AFAF"))))
     (modeline-mousable-minor-mode ((t (:foreground "#000000000000" :background "#FFFFD7D7AFAF"))))
     (highlight ((t (:background "#00005F5F5F5F"))))
     (bold ((t (:bold t))))
     (italic ((t (:italic t))))
     (bold-italic ((t (:bold t :italic t))))
     (region ((t (:background "#6C6C6C6C6C6C"))))
     (secondary-selection ((t (:background "#00005F5F8787"))))
     (underline ((t (:underline t))))
     (info-node ((t (:foreground "#CDCDCDCD0000" :bold t :italic t))))
     (info-menu-5 ((t (:underline t))))
     (info-xref ((t (:foreground "#CDCDCDCD0000" :bold t))))
     (diary-face ((t (:foreground "#FFFFAFAF0000"))))
     (calendar-today-face ((t (:underline t))))
     (holiday-face ((t (:background "#CDCD00000000"))))
     (show-paren-match-face ((t (:background "#00005F5F8787"))))
     (show-paren-mismatch-face ((t (:foreground "#E5E5E5E5E5E5" :background "#CDCD00000000"))))
     (font-lock-comment-face ((t (:foreground "#FFFF00000000"))))
     (font-lock-string-face ((t (:foreground "#FFFFAFAF0000"))))
     (font-lock-keyword-face ((t (:foreground "#0000FFFFFFFF"))))
     (font-lock-builtin-face ((t (:foreground "#AFAFD7D7D7D7"))))
     (font-lock-function-name-face ((t (:foreground "#0000FFFF8787"))))
     (font-lock-variable-name-face ((t (:foreground "#FFFFAFAF8787"))))
     (font-lock-type-face ((t (:foreground "#FFFFFFFF0000"))))
     (font-lock-constant-face ((t (:foreground "#FFFF87875F5F"))))
     (font-lock-warning-face ((t (:foreground "#FFFFD7D70000" :bold t))))
     (blank-space-face ((t (:background "#D0D0D0D0D0D0"))))
     (blank-tab-face ((t (:foreground "#000000000000" :background "#FFFFFFFFD7D7"))))
     (highline-face ((t (:background "#585858585858"))))
     (eshell-ls-directory-face ((t (:foreground "#0000CDCD0000" :bold t))))
     (eshell-ls-symlink-face ((t (:foreground "#0000CDCDCDCD" :bold t))))
     (eshell-ls-executable-face ((t (:foreground "#FFFFAFAF0000" :bold t))))
     (eshell-ls-readonly-face ((t (:foreground "#BCBCBCBCBCBC"))))
     (eshell-ls-unreadable-face ((t (:foreground "#A8A8A8A8A8A8"))))
     (eshell-ls-special-face ((t (:foreground "#CDCD0000CDCD" :bold t))))
     (eshell-ls-missing-face ((t (:foreground "#CDCD00000000" :bold t))))
     (eshell-ls-archive-face ((t (:foreground "#D7D75F5FD7D7" :bold t))))
     (eshell-ls-backup-face ((t (:foreground "#FFFFAFAF8787"))))
     (eshell-ls-product-face ((t (:foreground "#FFFFAFAF8787"))))
     (eshell-ls-clutter-face ((t (:foreground "#00000000EEEE" :bold t))))
     (sgml-start-tag-face ((t (:foreground "#0000FFFF8787"))))
     (custom-button-face ((t (:foreground "#E5E5E5E5E5E5"))))
     (sgml-ignored-face ((t (:foreground "#303030303030" :background "#949494949494"))))
     (sgml-doctype-face ((t (:foreground "#FFFFAFAF0000"))))
     (sgml-sgml-face ((t (:foreground "#CDCDCDCD0000"))))
     (vc-annotate-face-0046FF ((t (:foreground "#FFFFD7D7AFAF" :background "#000000000000"))))
     (custom-documentation-face ((t (:foreground "#E5E5E5E5E5E5"))))
     (sgml-end-tag-face ((t (:foreground "#AFAFFFFF0000"))))
     (linemenu-face ((t (:background "#4E4E4E4E4E4E"))))
     (sgml-entity-face ((t (:foreground "#FFFFD7D70000"))))
     (message-header-to-face ((t (:foreground "#FFFFFFFFFFFF" :bold t))))
     (message-header-cc-face ((t (:foreground "#FFFFFFFFFFFF"))))
     (message-header-subject-face ((t (:foreground "#FFFFFFFFD7D7" :bold t))))
     (message-header-newsgroups-face ((t (:foreground "#FFFFFFFFFFFF" :bold t :italic t))))
     (message-header-other-face ((t (:foreground "#AFAFFFFFFFFF"))))
     (message-header-name-face ((t (:foreground "#8787D7D7FFFF"))))
     (message-header-xheader-face ((t (:foreground "#00000000EEEE"))))
     (message-separator-face ((t (:foreground "#FFFFAFAF5F5F"))))
     (message-cited-text-face ((t (:foreground "#FFFFAFAFFFFF"))))
     (message-mml-face ((t (:foreground "#000087870000"))))
     (gnus-group-news-1-face ((t (:foreground "#E5E5E5E5E5E5" :bold t))))
     (gnus-group-news-1-empty-face ((t (:foreground "#E5E5E5E5E5E5"))))
     (gnus-group-news-2-face ((t (:foreground "#D7D7FFFFFFFF" :bold t))))
     (gnus-group-news-2-empty-face ((t (:foreground "#D7D7FFFFFFFF"))))
     (gnus-group-news-3-face ((t (:foreground "#D7D7AFAF8787" :bold t))))
     (gnus-group-news-3-empty-face ((t (:foreground "#D7D7AFAF8787"))))
     (gnus-group-news-4-face ((t (:foreground "#E5E5E5E5E5E5" :bold t))))
     (gnus-group-news-4-empty-face ((t (:foreground "#E5E5E5E5E5E5"))))
     (gnus-group-news-5-face ((t (:foreground "#FFFFD7D7AFAF" :bold t))))
     (gnus-group-news-5-empty-face ((t (:foreground "#FFFFD7D7AFAF"))))
     (gnus-group-news-6-face ((t (:foreground "#D7D7AFAF8787" :bold t))))
     (gnus-group-news-6-empty-face ((t (:foreground "#D7D7AFAF8787"))))
     (gnus-group-news-low-face ((t (:foreground "#0000CDCDCDCD" :bold t))))
     (gnus-group-news-low-empty-face ((t (:foreground "#0000CDCDCDCD"))))
     (gnus-group-mail-1-face ((t (:foreground "#E5E5E5E5E5E5" :bold t))))
     (gnus-group-mail-1-empty-face ((t (:foreground "#D0D0D0D0D0D0"))))
     (gnus-group-mail-2-face ((t (:foreground "#D7D7FFFFFFFF" :bold t))))
     (gnus-group-mail-2-empty-face ((t (:foreground "#D7D7FFFFFFFF"))))
     (gnus-group-mail-3-face ((t (:foreground "#D7D7AFAF8787" :bold t))))
     (gnus-group-mail-3-empty-face ((t (:foreground "#D7D7AFAF8787"))))
     (gnus-group-mail-low-face ((t (:foreground "#5F5F87878787" :bold t))))
     (gnus-group-mail-low-empty-face ((t (:foreground "#5F5F87878787"))))
     (gnus-summary-selected-face ((t (:background "#00005F5F8787" :underline t))))
     (gnus-summary-cancelled-face ((t (:foreground "#000000000000" :background "#BCBCBCBCBCBC"))))
     (gnus-summary-high-ticked-face ((t (:foreground "#B2B2B2B2B2B2" :bold t))))
     (gnus-summary-low-ticked-face ((t (:foreground "#B2B2B2B2B2B2" :bold t))))
     (gnus-summary-normal-ticked-face ((t (:foreground "#B2B2B2B2B2B2" :bold t))))
     (gnus-summary-high-ancient-face ((t (:foreground "#8787D7D7D7D7" :bold t))))
     (gnus-summary-low-ancient-face ((t (:foreground "#8787D7D7D7D7" :italic t))))
     (gnus-summary-normal-ancient-face ((t (:foreground "#8787D7D7D7D7"))))
     (gnus-summary-high-unread-face ((t (:bold t))))
     (gnus-summary-low-unread-face ((t (:italic t))))
     (gnus-summary-normal-unread-face ((t (nil))))
     (gnus-summary-high-read-face ((t (:foreground "#8787FFFF8787" :bold t))))
     (gnus-summary-low-read-face ((t (:foreground "#8787FFFF8787" :italic t))))
     (gnus-summary-normal-read-face ((t (:foreground "#8787FFFF8787"))))
     (gnus-splash-face ((t (:foreground "#FFFFD7D70000"))))
     (font-latex-bold-face ((t (nil))))
     (font-latex-italic-face ((t (nil))))
     (font-latex-math-face ((t (nil))))
     (font-latex-sedate-face ((t (:foreground "#DADADADADADA"))))
     (font-latex-string-face ((t (:foreground "#FFFFAFAF0000"))))
     (font-latex-warning-face ((t (:foreground "#FFFFD7D70000"))))
     (widget-documentation-face ((t (:foreground "#5F5FD7D75F5F"))))
     (widget-button-face ((t (:bold t))))
     (widget-field-face ((t (:background "#303030303030"))))
     (widget-single-line-field-face ((t (:background "#303030303030"))))
     (widget-inactive-face ((t (:foreground "#FFFFD7D7AFAF"))))
     (widget-button-pressed-face ((t (:foreground "#CDCD00000000"))))
     (custom-invalid-face ((t (:foreground "#CDCDCDCD0000" :background "#CDCD00000000"))))
     (custom-rogue-face ((t (:foreground "#FFFFAFAFD7D7" :background "#000000000000"))))
     (custom-modified-face ((t (:foreground "#E5E5E5E5E5E5" :background "#00000000EEEE"))))
     (custom-set-face ((t (:foreground "#00000000EEEE"))))
     (custom-changed-face ((t (:foreground "#FFFFD7D7AFAF" :background "#8787D7D7D7D7"))))
     (custom-saved-face ((t (:underline t))))
     (custom-state-face ((t (:foreground "#8787FFFF8787"))))
     (custom-variable-tag-face ((t (:foreground "#8787D7D7D7D7" :underline t))))
     (custom-variable-button-face ((t (:bold t :underline t))))
     (custom-face-tag-face ((t (:foreground "#E5E5E5E5E5E5" :underline t))))
     (custom-group-tag-face-1 ((t (:foreground "#FFFFAFAFD7D7" :underline t))))
     (custom-group-tag-face ((t (:foreground "#8787D7D7D7D7" :underline t))))
     (swbuff-current-buffer-face ((t (:foreground "#CDCD00000000" :bold t))))
     (ediff-current-diff-face-A ((t (:foreground "#AFAF00000000" :background "#8787FFFF8787"))))
     (ediff-current-diff-face-B ((t (:foreground "#87875F5FD7D7" :background "#CDCDCDCD0000"))))
     (ediff-current-diff-face-C ((t (:foreground "#E5E5E5E5E5E5" :background "#D7D75F5F5F5F"))))
     (ediff-current-diff-face-Ancestor ((t (:foreground "#000000000000" :background "#D7D700008787"))))
     (ediff-fine-diff-face-A ((t (:foreground "#000000008787" :background "#8787D7D7D7D7"))))
     (ediff-fine-diff-face-B ((t (:foreground "#000000000000" :background "#0000CDCDCDCD"))))
     (ediff-fine-diff-face-C ((t (:foreground "#000000000000" :background "#5F5FD7D7D7D7"))))
     (ediff-fine-diff-face-Ancestor ((t (:foreground "#000000000000" :background "#0000CDCD0000"))))
     (ediff-even-diff-face-A ((t (:foreground "#000000000000" :background "#D0D0D0D0D0D0"))))
     (ediff-even-diff-face-B ((t (:foreground "#E5E5E5E5E5E5" :background "#BCBCBCBCBCBC"))))
     (ediff-even-diff-face-C ((t (:foreground "#000000000000" :background "#D0D0D0D0D0D0"))))
     (ediff-even-diff-face-Ancestor ((t (:foreground "#E5E5E5E5E5E5" :background "#BCBCBCBCBCBC"))))
     (ediff-odd-diff-face-A ((t (:foreground "#E5E5E5E5E5E5" :background "#BCBCBCBCBCBC"))))
     (ediff-odd-diff-face-B ((t (:foreground "#000000000000" :background "#D0D0D0D0D0D0"))))
     (ediff-odd-diff-face-C ((t (:foreground "#E5E5E5E5E5E5" :background "#BCBCBCBCBCBC"))))
     (ediff-odd-diff-face-Ancestor ((t (:foreground "#000000000000" :background "#D0D0D0D0D0D0"))))
     (gnus-emphasis-bold ((t (:bold t))))
     (gnus-emphasis-italic ((t (:italic t))))
     (gnus-emphasis-underline ((t (:foreground "#E5E5E5E5E5E5" :background "#87875F5F0000"))))
     (gnus-emphasis-underline-bold ((t (:foreground "#000000000000" :background "#CDCDCDCD0000" :bold t :underline t))))
     (gnus-emphasis-underline-italic ((t (:foreground "#000000000000" :background "#CDCDCDCD0000" :italic t :underline t))))
     (gnus-emphasis-bold-italic ((t (:bold t :italic t))))
     (gnus-emphasis-underline-bold-italic ((t (:foreground "#000000000000" :background "#CDCDCDCD0000" :bold t :italic t :underline t))))
     (gnus-emphasis-highlight-words ((t (:foreground "#CDCDCDCD0000" :background "#000000000000"))))
     (gnus-signature-face ((t (:italic t))))
     (gnus-header-from-face ((t (:foreground "#FFFFD7D7AFAF"))))
     (gnus-header-subject-face ((t (:foreground "#FFFFD7D7AFAF" :bold t))))
     (gnus-header-newsgroups-face ((t (:foreground "#FFFFD7D7AFAF" :italic t))))
     (gnus-header-name-face ((t (:foreground "#E5E5E5E5E5E5"))))
     (gnus-header-content-face ((t (:foreground "#D7D7AFAF8787" :italic t))))
     (gnus-filterhist-face-1 ((t (nil))))
     (gnus-splash ((t (:foreground "#AFAF00000000"))))
     (gnus-cite-attribution-face ((t (:italic t))))
     (gnus-cite-face-1 ((t (:foreground "#AFAFD7D7D7D7"))))
     (gnus-cite-face-2 ((t (:foreground "#D7D7FFFFFFFF"))))
     (gnus-cite-face-3 ((t (:foreground "#FFFFFFFFD7D7"))))
     (gnus-cite-face-4 ((t (:foreground "#FFFFAFAFAFAF"))))
     (gnus-cite-face-5 ((t (:foreground "#8787FFFF8787"))))
     (gnus-cite-face-6 ((t (:foreground "#FFFFFFFFD7D7"))))
     (gnus-cite-face-7 ((t (:foreground "#FFFFAFAF0000"))))
     (gnus-cite-face-8 ((t (:foreground "#CDCD0000CDCD"))))
     (gnus-cite-face-9 ((t (:foreground "#FFFF8787FFFF"))))
     (gnus-cite-face-10 ((t (:foreground "#87875F5FD7D7"))))
     (gnus-cite-face-11 ((t (:foreground "#5F5FD7D7D7D7")))))))
(color-theme-tuantran)
