# THIS FILE IS FOR LOGIN SHELL

echo "[mptuan] Login Shell: Running $(realpath ${BASH_SOURCE[0]})"

# To have the same behavior for both login and non-login interactive shells
if [ -f ~/.bashrc ]; then
   source ~/.bashrc
fi
